baseURL = 'https://codebyred.github.io/'
languageCode = 'en-us'
title = 'CodebyRed | Blog'

[params]
  description = "My personal blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tags = "tags"
  author = "authors"