baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tags = "tags"
  author = "authors"