baseURL = 'https://codebyred.github.io/blog/'
languageCode = 'en-us'
title = 'CodebyRed | Blog'

[params]
  description = "My personal blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  tags = "tags"
  author = "authors"

[markup.highlight]
noClasses = false

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true

[outputs]
home = ["HTML"]      # keep HTML
page = ["HTML"]      # keep HTML
section = ["HTML"]