backend:
  name: github
  repo: codebyred/blog  # replace with your GitHub repo
  branch: main              # default branch

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content"
    create: true
    slug: "{{slug}}"
    format: toml
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["general"] }
      - { label: "Authors", name: "authors", widget: "list", default: ["Redoan"] }
      - { label: "Body", name: "body", widget: "markdown" }
